#Shulker menu matrix;
#s - shulker info;
#b - enable/disable button;
#l - whitelist/blacklist button
#i - item slot
#For plugin working, you need to specify all buttons and at least 1 slot for the item!
matrix:
  - "---------"
  - "--b-s-l--"
  - "---------"
  - "-iiiiiii-"
  - "-iiiiiii-"
  - "---------"

#You can change shulker menu and inventory
menu:
  settings: #Change shulker settings title
    name: "Shulker Settings"
  box: #Change shulker inventory title
    name: "%player%`s shulker"
  enable:
    type: STAINED_GLASS_PANE
    damage: 5
    meta:
      display-name: "§aEnable"
  disable:
    type: STAINED_GLASS_PANE
    damage: 14
    meta:
      display-name: "§cDisable"
  whitelist:
    type: STAINED_GLASS_PANE
    damage: 8
    meta:
      display-name: "§aMod §a[§fWhitelist§a]"
  blacklist:
    type: STAINED_GLASS_PANE
    damage: 15
    meta:
      display-name: "§aMod §a[§8Blacklist§a]"
  background: #Background items
    type: STAINED_GLASS_PANE
    damage: 0
    meta:
      display-name: " "

message:
  no-permissions: "You don`t have permissions!"
  player-not-found: "Player with this name was not found."
  shulker-give-ok: "Shulker successfully added."
  shulker-convert-ok: "Shulker successfully converted."
  shulker-convert-error: "You must have a shulker in your hand!"
  cmd-player-only: "This command can only be used by players"
  matrix-error: "Error with matrix! Contact with server Administrator!"